### ISSUE TITLE
[FR] - New script for alerting on unwatched movie/series requests from users

### ISSUE THREAD

**Issue by bobokun** [Drazzilb08/daps#127]
I'm sure there are folks like me who have users request media from Overseerr and end up forgetting to watch them after they get added. It would be nice to have a script that integrates with Overseerr and Tautulli to be able to generate a list of unwatched media based on what has been requested by the users. That way you can decide to either follow up with the user to see if they are still interested in watching or delete the media.

**Comment by Drazzilb08** [comment]
https://github.com/jorenn92/Maintainerr

I'm sure this is what you're looking for. :D
