### ISSUE TITLE
Bug - setting run in schedule

### ISSUE THREAD

**Issue by zhdenny** [Drazzilb08/daps#139]
dev v1.0.4

Reproduce problem:
1. While DAPS container is running, set a script to run in the "schedule:" section of the config file.
2. Within 60 seconds, DAPS will see the schedule change and begin running the script immediately as instructed.
3. The script runs and eventually finishes. Great.
4. within 60 seconds, the script runs AGAIN.....what? Not great. Can it NOT do this looping behavior? Instead, can setting a script to "run" in the schedule only tell DAPS to run the script a single time and not loop.

(I specifically witnessed this issue while setting `poster_renamerr` to `run` in the `schedule:`)

**Comment by Drazzilb08** [comment]
This was supposed to be fixed in the last push. Looks like I borked something. I'm going to relook at it when I get a chance.
