### ISSUE TITLE
Have the ability to filter what gets upgraded with Upgradinatorr. (Sonarr, Radarr)

### ISSUE THREAD

**Issue by TrojanHorsePower** [Drazzilb08/daps#155]
It would be pretty neat to filter out what gets upgraded. I see that an old issue #58 has been opened about this with a merge, but I don't see a way to do that in the new version. (feel free to correct me if I'm wrong)

Looking forward for your input, and thank you for these wonderful set of scripts.

**Comment by Drazzilb08** [comment]
Upgradiatorr will not push upgrades to items not monitored

Maybe a bit more details on what you're looking for specifically we can discuss this.

**Comment by TrojanHorsePower** [comment]
Well, I have upcoming releases or upcoming seasons monitored. Upgradiatorr was trying to upgrade an upcoming season of a show I have monitored. This specific title did not any previous seasons monitored or downloaded since I have seen them and deleted them for disk space. 
![image](https://github.com/Drazzilb08/daps/assets/106590776/dc7f1c3e-54d4-4bab-9d24-1b78bd768727)

Don't know how Upgradiatorr handles yet to be released movies that are monitored, since it hasn't touched them yet, but I'm assuming it will apply the same logic as it does for Sonarr. 

Ideally, I would like to just try to upgrade movies when their Minimum Availability is Released 
![image](https://github.com/Drazzilb08/daps/assets/106590776/641bf034-e6ab-415d-9441-2d0516a02502)

And for Sonarr I would like it to only upgrade episodes/seasons that have been released.

I'm not sure if that's possible in the Sonarr API, but I am sure that you can check what the minimum availability is via the Radarr API

Maybe the script does have this logic implemented, but since it happened to try to upgrade an upcoming season I assumed it doesn't do that (in case you can't filter that out because of a Sonarr API limitation)

**Comment by Drazzilb08** [comment]
Upgradinatorr doesn't work on the seasonal level. What it does via api is to smash the automatic search via the series level it will search whatever that button would search normally. This is solely filtered via the series being monitored or not. The same goes for radarr. If it's monitored it hits the automatic search if not monitored it skipped it.

**Comment by TrojanHorsePower** [comment]
Yeah, that would explain the behaviour I am seeing. So no plans on expanding upon that to filter status types? (MovieStatusType and SeriesStatusType respectively)

**Comment by Drazzilb08** [comment]
Not at this time no. The overall idea is to have upgradinatorr just search on a cycle for anything that is monitored filtering it down to search a select few items could be done with a much smaller more precise script.

**Comment by TrojanHorsePower** [comment]
Alright understandable. Thank you for replying.
