### ISSUE TITLE
Feature Request: split `unmatched assets` output in 10 or 20 segments.

### ISSUE THREAD

**Issue by BaukeZwart** [Drazzilb08/daps#156]
Would be a nice addition to the `unmatched_assets` script if we could split the log output in 10 or 20 individual segments (and if possible number them).
That makes it easy for a poster maker to claim a portion so we don't all work on the same first ones in the log.

This idea was raised after a Discord discussion starting here: 
https://discord.com/channels/492590071455940612/1213806644245569578/1226915811449376799

**Comment by Drazzilb08** [comment]
When I have time I'll look into this one.

**Comment by Drazzilb08** [comment]
Would you want segments to be in a single log or multiple logs/outputs. And how would you want them segmented in groups of 10-20 as stated? I mean I get the idea of what you're trying to accomplish on a creators standpoint but as a user it's easier to have a single log to know what to request. Maybe a more streamlined request process may be in order.
