### ISSUE TITLE
Less permissive file permissions for config.yml

### ISSUE THREAD

**Issue by danclay** [Drazzilb08/daps#168]
Currently this script seems to always chown the config dir to the provided UID and GID, and chmod to 777. config.yml contains sensitive information and should have an option to be less permissive (say 600 or 660). Perhaps a quick and simple solution could be to have the automatic chown and chmod disable if an environment variable is set and assume any user who uses said variable knows what they're doing permission wise?

**Comment by Drazzilb08** [comment]
I'll look into this more this evening. I will have to agree. This has been a huge learning journey for me. I started a year ago barely knowing how to install python.

**Comment by Drazzilb08** [comment]
Try dev out if there are any issues with 660, reopen the issue and let me know.
