### ISSUE TITLE
[Feat] Add collections to border_replacarr exclusion list

### ISSUE THREAD

**Issue by zarskie** [Drazzilb08/daps#169]
Currently only movies are being excluded would like for collections to be as well if possible. Thanks!

**Comment by Drazzilb08** [comment]
This hasn't been forgotten about, just been dumb busy recently.

**Comment by Drazzilb08** [comment]
I wonder if you ever looked into 
https://github.com/Drazzilb08/daps/blob/b74ce0b28fb321744ba8b126a6b5fe80d1540cf0/config/config.sample.yml#L223
it seems to already have been added at some point by me :)

If this is not what you're looking for lemme know

**Comment by zarskie** [comment]
Yeah this one isn't a big deal, I remember testing that my collection posters weren't being excluded but I've since removed the light posters and I'm not sure if this is even worth doing really.

**Comment by Drazzilb08** [comment]
Oh yeah, this was for collections, if you're not interested in it just go ahead and close the issue.
