### ISSUE TITLE
Add Apprise support to Jduparr

### ISSUE THREAD

**Issue by bakerboy448** [Drazzilb08/daps#170]

**Comment by Drazzilb08** [comment]
Why?

**Comment by bakerboy448** [comment]
Wider notification support?

**Comment by Drazzilb08** [comment]
Im open to a PR to make this happen. I've looked into it and realize it's a bit more of an undertaking than I'm able to put in. So for me it's a not at this time

**Comment by Drazzilb08** [comment]
@bakerboy448 
I'm recommending on this after this has been closed, but This has been added on the :dev branch currently only supports Discord/Notifiarr/email but if anybody is willing to add more support I'm totally game for it. I just do not have any other services to test on.
