### ISSUE TITLE
Add support for Gotify notification

### ISSUE THREAD

**Issue by LionCityGaming** [Drazzilb08/daps#175]
Is it possible to implement a way to get DAPS to send a Gotify notification after a succesful run?

**Comment by Drazzilb08** [comment]
I'm sure it is. I have no experience with that platform. I'm sure it's something that could be handled with apprise. I just need time to actually sit down and integrate that.

**Comment by Feramance** [comment]
I know bazarr handles gotify with apprise so you're right

**Comment by Drazzilb08** [comment]
After much digging and searching through this and making some local branches. 
I personally cannot create something to work well enough with this.
1st. I have limited knowledge on apprise (I could figure it out no problem, given enough time)
2nd. I don't use gotify and therefore wouldn't be able to test this out as I try to develop it
3rd. Finally I'm 100% down for somebody to possibly push a PR to make this happen while keeping the current functionality with discord/notifiarr
