### ISSUE TITLE
[Feat] add ignore movie/series to poster_cleanarr

### ISSUE THREAD

**Issue by zarskie** [Drazzilb08/daps#176]
I have a use case for having the option of ignoring specific movies/series to poster_cleanarr and currently from what I can tell only ignoring collections is supported. If possible it would be nice addition thanks!

**Comment by Drazzilb08** [comment]
Something that could be done. When I get back to coding (I hope soon) I have a todo list.

**Comment by zarskie** [comment]
thank you drazz

**Comment by Drazzilb08** [comment]
Updated dev branch, can you please test this to see if this is feature meets your expectations.
