### ISSUE TITLE
border_replacerr scheduled runs ignoring end date ranges

### ISSUE THREAD

**Issue by dweagle79** [Drazzilb08/daps#179]
When testing to add a holiday schedule in border_replacerr under normal run conditions, I discovered that certain date ranges are being ignored by the script.  Originally, I was testing under normal runs, but then switched to testing various dates by just running the script using docker at the command line with a small test source library and output folder.  The issue persists regardless of how daps is executed.

End date ranges of 7/1 through 7/12 will not run the schedule.  No errors are reported in dubug log, it just ignores those dates.

Example with screenshots below: range: (6/5-7/4)  will not run, but range: (6/5-7/13) will run.  

I would estimate probably trying 100 different dates/months. I tested this with and without several combinations of leading zeros in single digit dates.

![Screenshot from 2024-06-13 11-50-20](https://github.com/Drazzilb08/daps/assets/108494858/9d21a579-2afc-4d0c-b91d-43d0b35b9f64)

![Screenshot from 2024-06-13 11-49-41](https://github.com/Drazzilb08/daps/assets/108494858/efcf0fdb-1891-4f2e-9445-2749de264d73)

**Comment by Drazzilb08** [comment]
I'll be looking into this amongst all the other things I've got going on when I get a chance.

**Comment by Drazzilb08** [comment]
Neat, I can duplicate this. I'm working on it today. I'll let ya know if I get a fix.

**Comment by dweagle79** [comment]
Did several runs with varying date combinations similar to the ones I submitted. It seems to be running the schedule every time.
