### ISSUE TITLE
Notifiarr passthrough is giving a notification.name is required error with Plex backup script

### ISSUE THREAD

**Issue by BaukeZwart** [Drazzilb08/daps#180]
https://discord.com/channels/764440599066574859/1255781302016151592/1255781302016151592

**Comment by Drazzilb08** [comment]
I'll fix this per this conversation 

https://discord.com/channels/764440599066574859/1255781302016151592/1255995664496857109

**Comment by Drazzilb08** [comment]
Fix per this conversation

https://discord.com/channels/764440599066574859/1255781302016151592/1255996623134261320

**Comment by Drazzilb08** [comment]
This has been merged to both dev and master branches. Closing issue
