### ISSUE TITLE
Looks like changing cron schedule doesen't actually take effect immediately

### ISSUE THREAD

**Issue by s0len** [Drazzilb08/daps#189]
I've been using cron for my scheduling for quite a while and always had the issue of when I use
`cron (10 */1 * * *)`
It never actually triggers the script when i change the minute to 3-4 minutes after the current time. I thought it was due to some weird TN SCALE issue so I never actually bothered to report it but right now I'm running this through docker compose.

## How to reproduce
I change my minute marker of my cron schedule to current minute + 4 minutes.
I can see main.log updates with the new schedule.
After the minutes tick by the script border_replacer actually never runs until I restart my container.

**Comment by Drazzilb08** [comment]
Try reaccomplishing this with debug enabled for the main script.

**Comment by s0len** [comment]
[main.log](https://github.com/user-attachments/files/16829997/main.log)
Ah, debug shows exactly how it behaves. 56 was before i edited to 59

**Comment by Drazzilb08** [comment]
So is it acting as intended if so go ahead and close the issue.
